// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDyp7yO-0_VhZ22UHLOTK0spKHAcQUFvc',
    appId: '1:884067584071:web:c4520dd76fbbc6e6bac962',
    messagingSenderId: '884067584071',
    projectId: 'campus-navigation-system-s7s',
    authDomain: 'campus-navigation-system-s7s.firebaseapp.com',
    storageBucket: 'campus-navigation-system-s7s.firebasestorage.app',
    measurementId: 'G-ZB6GWPMFX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVtS9AV445fPlAppeH1RUWJDDgKgWuNc',
    appId: '1:884067584071:android:b20f2441702dbcb1bac962',
    messagingSenderId: '884067584071',
    projectId: 'campus-navigation-system-s7s',
    storageBucket: 'campus-navigation-system-s7s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_qkHmLnnRJ4uukJLudOa0p7P3lcAacVc',
    appId: '1:884067584071:ios:eab7887fc0a4b84fbac962',
    messagingSenderId: '884067584071',
    projectId: 'campus-navigation-system-s7s',
    storageBucket: 'campus-navigation-system-s7s.firebasestorage.app',
    iosBundleId: 'com.example.campusNavigationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_qkHmLnnRJ4uukJLudOa0p7P3lcAacVc',
    appId: '1:884067584071:ios:eab7887fc0a4b84fbac962',
    messagingSenderId: '884067584071',
    projectId: 'campus-navigation-system-s7s',
    storageBucket: 'campus-navigation-system-s7s.firebasestorage.app',
    iosBundleId: 'com.example.campusNavigationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDyp7yO-0_VhZ22UHLOTK0spKHAcQUFvc',
    appId: '1:884067584071:web:fd36dc19f5047d83bac962',
    messagingSenderId: '884067584071',
    projectId: 'campus-navigation-system-s7s',
    authDomain: 'campus-navigation-system-s7s.firebaseapp.com',
    storageBucket: 'campus-navigation-system-s7s.firebasestorage.app',
    measurementId: 'G-LF4115LZ48',
  );
}
